### ISSUE TITLE
Directives not being parsed

### ISSUE THREAD

**Issue by dio5** [magebitcom/vsf-aheadworks-blog-indexer#1]
Hi,

Thanks for the vsf blog module & indexer.

It looks to me magento directives in the wysiwygs are not being parsed when indexed, eg:

```
{{store url=""}} 
{{media url=""}}
```
They stay like that in ES thus not rendering correct paths.

Any plans on fixing this?

Thanks
Dieter

**Comment by KristofersOzolinsMagebit** [comment]
Hey @dio5 
Sorry for late response.

This has been fixed in v1.0.3. If you're still experiencing issues, let us know!
